name: Publish
on:
  push:
    branches:
      - main
jobs:
  publish-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Fix remote
        run: git remote set-url origin git@github.com:Gerrit0/lists.git
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Install
        run: yarn
      - name: Rebuild markdown site
        run: yarn build
      - name: Publish
        run: yarn site
